In [55]:
import pandas as pd
import numpy as np

In [56]:
salaries = pd.read_csv("Salaries.csv")

In [57]:
salaries.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411,0,400184,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966,245132,137811,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739,106088,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.7,198307,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134402,9737,182235,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [75]:
salaries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
Id                  148654 non-null int64
EmployeeName        148654 non-null object
JobTitle            148654 non-null object
BasePay             147174 non-null object
OvertimePay         82551 non-null object
OtherPay            113436 non-null object
Benefits            111442 non-null object
TotalPay            148286 non-null float64
TotalPayBenefits    148624 non-null float64
Year                148654 non-null int64
Notes               0 non-null float64
Agency              148654 non-null object
Status              38119 non-null object
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB

In [70]:
salaries.fillna(0)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411,0,400184,0,567595.43,567595.43,2011,0.0,San Francisco,0
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966,245132,137811,0,538909.28,538909.28,2011,0.0,San Francisco,0
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739,106088,16452.6,0,335279.91,335279.91,2011,0.0,San Francisco,0
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.7,198307,0,332343.61,332343.61,2011,0.0,San Francisco,0
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134402,9737,182235,0,326373.19,326373.19,2011,0.0,San Francisco,0
5,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602,8601,189083,0,316285.74,316285.74,2011,0.0,San Francisco,0
6,7,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492,89062.9,134426,0,315981.05,315981.05,2011,0.0,San Francisco,0
7,8,DAVID KUSHNER,DEPUTY DIRECTOR OF INVESTMENTS,256577,0,51322.5,0,307899.46,307899.46,2011,0.0,San Francisco,0
8,9,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176933,86362.7,40132.2,0,303427.55,303427.55,2011,0.0,San Francisco,0
9,10,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262,0,17115.7,0,302377.73,302377.73,2011,0.0,San Francisco,0
10,11,ARTHUR KENNEY,"ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",194999,71344.9,33149.9,0,299494.17,299494.17,2011,0.0,San Francisco,0
11,12,PATRICIA JACKSON,CAPTAIN III (POLICE DEPARTMENT),99722,87082.6,110804,0,297608.92,297608.92,2011,0.0,San Francisco,0
12,13,EDWARD HARRINGTON,EXECUTIVE CONTRACT EMPLOYEE,294580,0,0,0,294580.02,294580.02,2011,0.0,San Francisco,0
13,14,JOHN MARTIN,DEPARTMENT HEAD V,271329,0,21342.6,0,292671.62,292671.62,2011,0.0,San Francisco,0
14,15,DAVID FRANKLIN,"BATTALION CHIEF, (FIRE DEPARTMENT)",174873,74050.3,37424.1,0,286347.05,286347.05,2011,0.0,San Francisco,0
15,16,RICHARD CORRIEA,"COMMANDER III, (POLICE DEPARTMENT)",198778,73478.2,13957.6,0,286213.86,286213.86,2011,0.0,San Francisco,0
16,17,AMY HART,DEPARTMENT HEAD V,268605,0,16115.9,0,284720.43,284720.43,2011,0.0,San Francisco,0
17,18,SEBASTIAN WONG,"CAPTAIN, EMERGENCYCY MEDICAL SERVICES",140547,119397,18625.1,0,278569.21,278569.21,2011,0.0,San Francisco,0
18,19,MARTY ROSS,"BATTALION CHIEF, (FIRE DEPARTMENT)",168693,69626.1,38115.5,0,276434.22,276434.22,2011,0.0,San Francisco,0
19,20,ELLEN MOFFATT,ASSISTANT MEDICAL EXAMINER,257511,880.16,16159.5,0,274550.25,274550.25,2011,0.0,San Francisco,0
20,21,VENUS AZAR,ASSISTANT MEDICAL EXAMINER,257510,0,16679.8,0,274190.27,274190.27,2011,0.0,San Francisco,0
21,22,JUDY MELINEK,ASSISTANT MEDICAL EXAMINER,257510,377.21,15883.6,0,273771.21,273771.21,2011,0.0,San Francisco,0
22,23,GEORGE GARCIA,"CAPTAIN, FIRE SUPPRESSION",140547,93200.6,39955.2,0,273702.71,273702.71,2011,0.0,San Francisco,0
23,24,VICTOR WYRSCH,"BATTALION CHIEF, (FIRE DEPARTMENT)",168693,77896.1,24083.9,0,270672.63,270672.63,2011,0.0,San Francisco,0
24,25,JOSEPH DRISCOLL,"CAPTAIN, FIRE SUPPRESSION",140547,97868.8,31909.3,0,270324.91,270324.91,2011,0.0,San Francisco,0
25,26,GREGORY SUHR,CHIEF OF POLICE,256470,0,11522.2,0,267992.59,267992.59,2011,0.0,San Francisco,0
26,27,JOHN HANLEY,"CAPTAIN, FIRE SUPPRESSION",92080.8,40008,133696,0,265784.56,265784.56,2011,0.0,San Francisco,0
27,28,RAYMOND GUZMAN,"BATTALION CHIEF, (FIRE DEPARTMENT)",168693,80706.9,16064,0,265463.46,265463.46,2011,0.0,San Francisco,0
28,29,DENISE SCHMITT,DEPUTY CHIEF III (POLICE DEPARTMENT),261718,0,2357,0,264074.60,264074.60,2011,0.0,San Francisco,0
29,30,MONICA FIELDS,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",246226,0,15140.5,0,261366.14,261366.14,2011,0.0,San Francisco,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148624,148625,Lorraine Rosenthal,Senior Clerk,0.00,0.00,12.89,0.00,12.89,12.89,2014,0.0,San Francisco,PT
148625,148626,Renato C Gurion,Registered Nurse,0.00,0.00,6.00,1.24,6.00,7.24,2014,0.0,San Francisco,PT
148626,148627,Paulet Gaines,Account Clerk,0.00,0.00,0.00,0.00,0.00,0.00,2014,0.0,San Francisco,PT
148627,148628,Brett A Lundberg,General Laborer,0.00,0.00,0.00,0.00,0.00,0.00,2014,0.0,San Francisco,PT
148628,148629,Mark W Mcclure,General Laborer,0.00,0.00,0.00,0.00,0.00,0.00,2014,0.0,San Francisco,PT
148629,148630,Elizabeth Iniguez,Transcriber Typist,0.00,0.00,0.00,0.00,0.00,0.00,2014,0.0,San Francisco,PT
148630,148631,Randy J Keys,Carpenter,0.00,0.00,0.00,0.00,0.00,0.00,2014,0.0,San Francisco,PT
148631,148632,Andre M Johnson,Communications Dispatcher 1,0.00,0.00,0.00,0.00,0.00,0.00,2014,0.0,San Francisco,PT
148632,148633,Sharon D Owens-Webster,Protective Services Worker,0.00,0.00,0.00,0.00,0.00,0.00,2014,0.0,San Francisco,PT
148633,148634,Edward Ferdinand,General Laborer,0.00,0.00,0.00,0.00,0.00,0.00,2014,0.0,San Francisco,PT
148634,148635,David M Turner,Transit Car Cleaner,0.00,0.00,0.00,0.00,0.00,0.00,2014,0.0,San Francisco,PT
148635,148636,James S Kibblewhite,General Laborer,0.00,0.00,0.00,0.00,0.00,0.00,2014,0.0,San Francisco,PT
148636,148637,Andrew J Enzi,Arborist Technician,0.00,0.00,0.00,0.00,0.00,0.00,2014,0.0,San Francisco,PT
148637,148638,Kadeshra D Green,Transit Fare Inspector,0.00,0.00,0.00,0.00,0.00,0.00,2014,0.0,San Francisco,PT
148638,148639,Lennard B Hutchinson,Electrician,0.00,0.00,0.00,0.00,0.00,0.00,2014,0.0,San Francisco,PT
148639,148640,Richard A Talbert,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,0.0,San Francisco,PT
148640,148641,Charlene D Mccully,Parking Control Officer,0.00,0.00,0.00,0.00,0.00,0.00,2014,0.0,San Francisco,PT
148641,148642,Raphael Marquis Goins,Museum Guard,0.00,0.00,0.00,0.00,0.00,0.00,2014,0.0,San Francisco,PT
148642,148643,Dominic C Marquez,Sign Worker,0.00,0.00,0.00,0.00,0.00,0.00,2014,0.0,San Francisco,PT
148643,148644,Kim Brewer,Parking Control Officer,0.00,0.00,0.00,0.00,0.00,0.00,2014,0.0,San Francisco,PT
148644,148645,Randy D Winn,"Stationary Eng, Sewage Plant",0.00,0.00,0.00,0.00,0.00,0.00,2014,0.0,San Francisco,PT
148645,148646,Carolyn A Wilson,Human Services Technician,0.00,0.00,0.00,0.00,0.00,0.00,2014,0.0,San Francisco,PT
148646,148647,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,0.0,San Francisco,0
148647,148648,Joann Anderson,Communications Dispatcher 2,0.00,0.00,0.00,0.00,0.00,0.00,2014,0.0,San Francisco,PT
148648,148649,Leon Walker,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,0.0,San Francisco,PT
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,0.0,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,0.0,San Francisco,0
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,0.0,San Francisco,0
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,0.0,San Francisco,0
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014,0.0,San Francisco,PT

In [68]:
salaries["BasePay"] = pd.to_numeric(salaries["BasePay"])

ValueError: Unable to parse string "Not Provided" at position 148646

In [71]:
salaries = salaries.replace(0,np.NaN)

In [74]:
salaries.BasePay.head()

0    167411
1    155966
2    212739
3     77916
4    134402
Name: BasePay, dtype: object

In [63]:
salaries.Agency.value_counts()

San Francisco    148654
Name: Agency, dtype: int64

In [43]:
salaries.Year.value_counts()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

In [53]:
salaries.Status.value_counts()
#Include NaN values when counting? Should be considered another category.
#Change missing values to "-1"?

FT    22334
PT    15785
Name: Status, dtype: int64

In [54]:
len(salaries)

148654

In [76]:
salaries.BasePay.value_counts()

0.00         423
54703.00     327
55026.0      297
48472.4      210
65448.0      153
121068.0     152
68391.0      152
88374.0      151
51492.8      143
94191.0      137
116584.0     127
105934.66    117
105934.67    114
51502.0      110
67948.0      109
63995.0      103
60206.6      101
86840.0       95
105934.65     94
72144.0       86
116956.71     85
81830.0       84
79222.0       82
88062.0       82
112703.74     79
83160.0       77
61128.0       77
109783.86     74
57630.6       73
77580.4       71
            ...
69095.97       1
88825.96       1
97848.32       1
33100.35       1
90174.48       1
64900.3        1
61086.21       1
19265.11       1
76659.2        1
149921.21      1
81442.28       1
61995.8        1
7348.12        1
181955.77      1
9600.97        1
93386.26       1
103975.81      1
13713.47       1
88886.04       1
87018.3        1
65646.58       1
63338.98       1
11179.30       1
53161.24       1
130904.62      1
59099.7        1
60109.11       1
2875.83        1
47072.04       1
10684.5        1
Name: BasePay, dtype: int64